<a href="https://colab.research.google.com/github/rubelhosen79/AI-Engineering-Bootcamp/blob/main/2025_05_18T11_03_57_360Z_Module_2_Live_Class_1_Fixing_Vector_Matrix_Shape_Errors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🛠️ Fixing Vector and Matrix Shape Mismatches


This notebook explains what to do when vector or matrix operations fail due to shape mismatches.
You'll learn:
- Why these errors happen
- How to fix mismatched shapes
- Padding, truncating, reshaping, and broadcasting

Includes Bengali analogies to help you understand better.


## 🔧 1. Vector Addition or Multiplication – Length Mismatch

In [ ]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5])
a + b  # ValueError

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

### ✅ Fix Option(s):

In [ ]:
b_padded = np.pad(b, (0, len(a) - len(b)), constant_values=0)
print(a + b_padded)

[5 7 3]


In [ ]:
min_len = min(len(a), len(b))
print(a[:min_len] + b[:min_len])

[5 7]


### Bengali Analogy:
তুমি যদি ৩টা সংখ্যা নাও আর আমি ২টা দিই, তাহলে একটাকে শূন্য ধরা বা কেটে ফেলা দরকার তুলনা করতে।

## 🔧 2. Matrix Addition or Element-wise Multiplication – Shape Mismatch

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6, 7]])
A + B  # ValueError

ValueError: operands could not be broadcast together with shapes (2,2) (1,3) 

### ✅ Fix Option(s):

In [ ]:
def pad_matrix(mat, target_shape, pad_value=0):
    padded = np.full(target_shape, pad_value)
    padded[:mat.shape[0], :mat.shape[1]] = mat
    return padded

A_fixed = pad_matrix(A, (2, 3))
B_fixed = pad_matrix(B, (2, 3))
print(A_fixed + B_fixed)

[[6 8 7]
 [3 4 0]]


### Bengali Analogy:
দুই ছাত্রের নামের তালিকার কলাম সংখ্যা না মেললে, তালিকা মেলানো যাবে না।

## 🔧 3. Vector Dot Product – Length Mismatch

In [ ]:
np.dot([1, 2, 3], [4, 5])  # ValueError

ValueError: shapes (3,) and (2,) not aligned: 3 (dim 0) != 2 (dim 0)

### ✅ Fix Option(s):

In [ ]:
b_padded = np.pad([4, 5], (0, 1))
print(np.dot([1, 2, 3], b_padded))

14


### Bengali Analogy:
তুমি যদি তিনটা প্রশ্ন করো আর আমি যদি দুটো উত্তর দিই, সব প্রশ্নের উত্তর হবে না।

## 🔧 4. Matrix Multiplication – Column ≠ Row

In [ ]:
A = np.array([[1, 2]])
B = np.array([[3, 4]])
np.dot(A, B)  # ValueError

ValueError: shapes (1,2) and (1,2) not aligned: 2 (dim 1) != 1 (dim 0)

### ✅ Fix Option(s):

In [ ]:
B = np.array([[3], [4]])
print(np.dot(A, B))

[[11]]


### Bengali Analogy:
প্রশ্নের সংখ্যা ২, কিন্তু উত্তরের সংখ্যা ১ — মিলবে না।

## 🔧 5. Broadcasting Failures

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([10, 20])
A + B  # ValueError

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

### ✅ Fix Option(s):

In [ ]:
B_fixed = np.array([[10, 20, 0]])
print(A + B_fixed)

[[11 22  3]
 [14 25  6]]


### Bengali Analogy:
এক প্রশ্ন যদি সব ছাত্রের জন্য হয়, তাহলে সেটাকে সবার জন্য কপি করা যায়।